/**
 * Curated icon lookup for placeholder card art (see PlaceholderArt.tsx).
 * Exact-name matches first (tribal creature types, themes, etc.), falling
 * back to a sensible default per category. This is intentionally a
 * hand-picked table rather than something clever/derived — the goal is
 * charm, not correctness, and it's trivially replaced by real per-card
 * artwork later without touching any other code (see cards.json's
 * `artPrompt` field for what the eventual commissioned art should show).
 */
import type { Category, ModifierCard } from '../domain/cardTypes'

const NAME_ICONS: Record<string, string> = {
  // Tribal
  'Tribal Angel': '👼',
  'Tribal Demon': '😈',
  'Tribal Dragon': '🐉',
  'Tribal Elf': '🧝',
  'Tribal Goblin': '👺',
  'Tribal Merfolk': '🧜',
  'Tribal Zombie': '🧟',
  'Tribal Vampire': '🧛',
  'Tribal Human': '🧑',
  'Tribal Soldier': '💂',
  'Tribal Sliver': '🪱',
  'Tribal Elemental': '🔥',
  'Tribal Spirit': '👻',
  'Tribal Wizard': '🧙',
  'Tribal Rogue': '🥷',
  'Tribal Warrior': '⚔️',
  'Tribal Knight': '🛡️',
  'Tribal Cleric': '🙏',
  'Tribal Druid': '🌿',
  'Tribal Shaman': '🪘',
  'Tribal Beast': '🐻',
  'Tribal Bird': '🐦',
  'Tribal Cat': '🐱',
  'Tribal Dog': '🐶',
  'Tribal Horror': '👹',
  'Tribal Construct': '🤖',
  'Tribal Golem': '🗿',
  'Tribal Minotaur': '🐂',
  'Tribal Mutant': '🧬',
  'Tribal Faerie': '🧚',
  'Tribal Kithkin': '🍀',
  'Tribal Treefolk': '🌳',
  'Tribal Eldrazi': '🐙',
  'Tribal Phyrexian': '⚙️',
  'Tribal Orc': '👹',
  'Tribal Giant': '🏔️',
  'Tribal Ogre': '👹',
  'Tribal Sphinx': '🦁',
  'Tribal Devil': '👿',
  'Tribal Kraken': '🐙',
  'Tribal Leviathan': '🐳',
  'Tribal Snake': '🐍',
  'Tribal Insect': '🐛',
  'Tribal Fungus': '🍄',
  'Tribal Dinosaur': '🦖',
  'Tribal God': '⚡',
  'Tribal Advisor': '📜',
  'Tribal Samurai': '🗡️',
  'Tribal Ninja': '🥷',
  'Tribal Moonfolk': '🌙',
  'Tribal Djinn': '🧞',
  'Tribal Efreet': '🔥',
  'Tribal Frog': '🐸',
  'Tribal Hydra': '🐍',
  'Tribal Lizard': '🦎',
  'Tribal Rat': '🐀',
  'Tribal Scarecrow': '🎃',
  'Tribal Serpent': '🐍',
  'Tribal Unicorn': '🦄',
  // Themes
  'Theme Lifegain': '❤️',
  'Theme Sacrifice': '🔪',
  'Theme Tokens': '🎭',
  'Theme Voltron': '🦾',
  'Theme Reanimator': '⚰️',
  'Theme Stax': '⛓️',
  'Theme Control': '🎛️',
  'Theme Aggro': '💥',
  'Theme Combo': '🧩',
  'Theme Enchantress': '📿',
  'Theme Artifacts': '⚙️',
  'Theme Mill': '📚',
  'Theme Landfall': '🏔️',
  'Theme Spellslinger': '🔮',
  'Theme Mutate': '🧬',
  'Theme Group Hug': '🤗',
  'Theme Steal & Copy': '🎭',
  'Theme Proliferate': '➕',
  'Theme Poison/Infect': '☠️',
  'Theme Superfriends': '🦸',
  'Theme Chaos': '🌀',
  'Theme Cascade': '🌊',
  'Theme Storm': '⛈️',
  'Theme Blink': '✨',
  'Theme Energy': '⚡',
  'Theme Shrines': '⛩️',
  'Theme Gates': '🚪',
  'Theme Defenders': '🛡️',
  'Theme Treasure': '💰',
  'Theme Clue': '🔎',
  'Theme Food': '🍖',
  'Theme Historic Spells': '📖',
  'Theme Dungeon & Venture': '🗝️',
  'Theme Equipment': '🗡️',
  'Theme Madness': '🃏',
  'Theme Discard Matters': '🗑️',
  'Theme Legendary Matters': '👑',
  'Theme Exile Matters': '🌫️',
  'Theme Morph & Manifest': '🎭',
  'Theme Sneak Attack & Cheat Costs': '🥷',
  'Theme Damage Doublers': '✖️',
  'Theme Life Swap & Exchange': '🔄',
  // Colours
  'Colour W': '☀️',
  'Colour U': '🌊',
  'Colour B': '💀',
  'Colour R': '🔥',
  'Colour G': '🌳',
  // Score cards
  '+2 Points for Winning the Game': '🏆',
  'Must have Flying': '🕊️',
  'Only Creatures': '🐾',
}

const CATEGORY_ICONS: Record<Category, string> = {
  rarity: '💎',
  price: '💰',
  deckCount: '📊',
  colour: '🎨',
  tribal: '👥',
  theme: '✨',
  manaValue: '🔷',
  salt: '🧂',
  deckArt: '🖼️',
  commanderArt: '👑',
  deckComposition: '🃏',
  untyped: '🌀',
}

export function getCardIcon(card: ModifierCard): string {
  return NAME_ICONS[card.name] ?? CATEGORY_ICONS[card.category] ?? '❔'
}
